### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by isysd** [deginner/tigoctm#3]
Chose colors and a general template for the Tigo CTM brand. This will be used to create the logo, as well as the website design.

Logo project (blocked): https://bitbucket.org/deginner/tigo-logo

- [ ] Primary and secondary color
- [ ] Any thematic elements (aside from logo referenced above)

**Comment by cindy-zimmerman** [comment]
Primary Color - White
Secondary color - Red
Tertiary colors - Grey and Black
As of this moment I don't have any other thematic elements aside from the logo
